// import { useContext } from 'react'
import Head from "next/head";
import { useRouter } from 'next/navigation';
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
// import { Button, EditIcon } from '@/components/mui'
import Layout from "@/components/Layout";
import Heading from "@/components/Heading";
import Paragraph from "@/components/Paragraph";
import QueryBoundaries from "@/components/QueryBoundaries";
import OrderList from "@/components/OrderList";
import { dehydrate, QueryClient, useQuery } from "@tanstack/react-query";
import { fetchOrders } from "@/lib/api-functions/server/orders/queries";
import { STORAGE_KEY } from "@/lib/tq/orders/settings";


// import OrderForm from "@/components/forms/OrderForm";
import { useAdd } from "@/lib/tq/orders/mutations"

// const inter = Inter({ subsets: ['latin'] })
export default function AddOrder() {
  const router = useRouter();
  const addMutation = useAdd();

  const submitHandler = (data) => {
    addMutation.mutate(data);
    router.push("/admin/orders/");
  };
  //   const {
  //     showMessage
  //   } = useContext(UIContext)
  return (
    <>
      <Head>
        <title>Aidan Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h1">Add Order</Heading>
        
        {/* <OrderForm submitHandler={submitHandler} /> */}
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {},
  };
}
