// import {useContext} from 'react'
import Head from "next/head";

import { withPageAuthRequired } from "@auth0/nextjs-auth0";

import { dehydrate, QueryClient } from "@tanstack/react-query";
import { getOrdersQuery } from "@/lib/api-functions/server/orders/queries";
import { USER_ORDERS_STORAGE_KEY, STORAGE_KEY } from "@/lib/tq/orders/settings";

import Layout from "@/components/Layout";
import Heading from "@/components/Heading";
import QueryBoundaries from "@/components/QueryBoundaries";
import OrderList from "@/components/OrderList";
import { useDelete } from "@/lib/tq/orders/mutations";

export default function AdminOrderList() {
  const removeMutation = useDelete();

  const removeHandler = (id) => {
    // console.log('in handler', args);
    removeMutation.mutate(id);
  };
  return (
    <>
      <Head>
        <title>Admin List Orders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2">Admin List Orders</Heading>
        <QueryBoundaries>
          <OrderList deleteHandler={removeHandler} />
        </QueryBoundaries>
      </Layout>
    </>
  );
}

export const getServerSideProps = withPageAuthRequired({
  async getServerSideProps(context) {
    const orders = await getOrdersQuery().catch((err) => console.log(err));

    const queryClient = new QueryClient();

    await queryClient.setQueryData(
      [STORAGE_KEY],
      JSON.parse(JSON.stringify(orders))
    );

    return {
      props: {
        dehydratedState: dehydrate(queryClient),
      },
    };
  },
});