import Head from "next/head";

import { withPageAuthRequired } from "@auth0/nextjs-auth0";

import { dehydrate, QueryClient } from "@tanstack/react-query";
import { getAllBasketsQuery } from "@/lib/api-functions/server/baskets/queries";
import { STORAGE_KEY } from "@/lib/tq/baskets/settings";
import QueryBoundaries from "@/components/QueryBoundaries";
import Basket from "@/components/Basket";

import Layout from "@/components/Layout";
import Heading from "@/components/Heading";
import { useDelete } from "@/lib/tq/baskets/mutations";

export default function AdminBasketList() {
  const removeMutation = useDelete();

  const removeHandler = (id) => {
    // console.log('in handler', args);
    removeMutation.mutate(id);
  };
  return (
    <>
      <Head>
        <title>Admin List Baskets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2">Admin List Baskets</Heading>
        <QueryBoundaries>
          <Basket deleteHandler={removeHandler} />
        </QueryBoundaries>
      </Layout>
    </>
  );
}

export const getServerSideProps = withPageAuthRequired({
  async getServerSideProps(context) {
    const baskets = await getAllBasketsQuery().catch((err) => console.log(err));

    const queryClient = new QueryClient();

    await queryClient.setQueryData(
      [STORAGE_KEY],
      JSON.parse(JSON.stringify(baskets))
    );

    return {
      props: {
        dehydratedState: dehydrate(queryClient),
      },
    };
  },
});