// import { useContext } from 'react'
import Head from 'next/head'
import { withPageAuthRequired, getSession } from "@auth0/nextjs-auth0";
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
import Link from 'next/link'
import { Button, EditIcon } from '@/components/mui'
import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import Paragraph from '@/components/Paragraph';
import QueryBoundaries from "@/components/QueryBoundaries";
// import ProductList from "@/components/ProductList";
import UserDisplay from "@/components/UserDisplay";
import { dehydrate, QueryClient, useQuery } from '@tanstack/react-query'
import { fetchProducts } from "@/lib/api-functions/server/products/queries";
import { STORAGE_KEY } from "@/lib/tq/products/settings";
// import { UIContext } from '@/components/contexts/UI.context';


// const inter = Inter({ subsets: ['latin'] })
export default function ProfilePage({ ssd, sess }) {

  // const {
  //   showMessage
  // } = useContext(UIContext)
  return (
    <>
      <Head>
        <title>Eclectic Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component='h2'>Profile</Heading>
        
        {/* <Button variant="contained" onClick={() => showMessage({
          type: 'error',
          string: 'You clicked the toast test button.'
        })}><EditIcon />Toast Test Button</Button> */}
        <QueryBoundaries>
          <UserDisplay user={ssd} />
        </QueryBoundaries>
        <Paragraph>There should be a profile above here, or you borked the Auth0 connection.</Paragraph>
      </Layout>
    </>
  )
}

export const getServerSideProps = withPageAuthRequired({
  async getServerSideProps(context) {
    // Getting user data from Auth0
    const session = await getSession(context.req, context.res);

    return {
      props: { ssd: session.user, sess: JSON.parse(JSON.stringify(session)) },
    };
  },
});