import Head from 'next/head'
import { withPageAuthRequired, getSession } from "@auth0/nextjs-auth0";
import Heading from '@/components/Heading';
// import Paragraph from '@/components/Paragraph';
import QueryBoundaries from "@/components/QueryBoundaries";
import UserDisplay from "@/components/UserDisplay";
import Layout from '@/components/Layout';
import backgroundImg from "@/images/mountain_dark.jpg";

export default function ProfilePage({ ssd, sess }) {

  return (
    <div style={{
      backgroundImage: `url(${backgroundImg.src})`,
      backgroundSize: "cover",
      backgroundAttachment: "fixed",
      width: "100vw"}}>
      <Head>
        <title>Eclectic Shop | Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component='h2' sx={{ color: "white" }}>Profile</Heading>
        <QueryBoundaries>
          <UserDisplay user={ssd} />
        </QueryBoundaries>
        {/* <pre>{JSON.stringify(sess, null, 2)}</pre> */}
        {/* <Paragraph>There should be a profile above here, or you borked the Auth0 connection.</Paragraph> */}
      </Layout>
    </div>
  )
}

export const getServerSideProps = withPageAuthRequired({
  async getServerSideProps(context) {
    // Getting user data from Auth0
    const session = await getSession(context.req, context.res);

    return {
      props: { ssd: session.user, sess: JSON.parse(JSON.stringify(session)) },
    };
  },
});